import React, { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  Alert,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { useRouter } from 'expo-router';
import { saveProfile, setActiveProfileId, saveVital } from '../services/supabaseStorage';
import { Profile } from '../types';

export default function AddProfileScreen() {
  const router = useRouter();
  const [name, setName] = useState('');
  const [age, setAge] = useState('');
  const [weight, setWeight] = useState('');
  const [height, setHeight] = useState('');

  const handleSave = async () => {
    // Validation
    if (!name.trim()) {
      Alert.alert('Error', 'Please enter a name');
      return;
    }

    if (!age || isNaN(Number(age)) || Number(age) <= 0 || Number(age) > 150) {
      Alert.alert('Error', 'Please enter a valid age (1-150)');
      return;
    }

    if (weight && (isNaN(Number(weight)) || Number(weight) <= 0)) {
      Alert.alert('Error', 'Please enter a valid weight');
      return;
    }

    if (height && (isNaN(Number(height)) || Number(height) <= 0)) {
      Alert.alert('Error', 'Please enter a valid height');
      return;
    }

    try {
      // Create new profile (ID will be generated by Supabase)
      const newProfile: Profile = {
        id: '', // Will be set by saveProfile
        name: name.trim(),
        age: Number(age),
        relation: 'Family', // Default relation
      };

      await saveProfile(newProfile);
      await setActiveProfileId(newProfile.id); // Now has the generated UUID

      // Save weight and height as vitals if provided
      if (weight) {
        await saveVital(newProfile.id, {
          type: 'weight',
          value: Number(weight),
          unit: 'kg',
          date: new Date().toISOString(),
          isDaily: false,
        });
      }

      if (height) {
        await saveVital(newProfile.id, {
          type: 'height',
          value: Number(height),
          unit: 'cm',
          date: new Date().toISOString(),
          isDaily: false,
        });
      }

      // Save age as a vital
      await saveVital(newProfile.id, {
        type: 'age',
        value: Number(age),
        unit: 'years',
        date: new Date().toISOString(),
        isDaily: false,
      });

      Alert.alert('Success', 'Profile created successfully!', [
        {
          text: 'OK',
          onPress: () => router.back(),
        },
      ]);
    } catch (error) {
      console.error('Failed to create profile:', error);
      Alert.alert('Error', 'Failed to create profile. Please try again.');
    }
  };

  return (
    <KeyboardAvoidingView
      style={styles.container}
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
    >
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()}>
          <Text style={styles.backText}>✕ Cancel</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Add Profile</Text>
        <View style={{ width: 60 }} />
      </View>

      <ScrollView
        style={styles.content}
        contentContainerStyle={styles.contentContainer}
        keyboardShouldPersistTaps="handled"
      >
        {/* Name Field */}
        <View style={styles.fieldGroup}>
          <Text style={styles.label}>Name *</Text>
          <TextInput
            style={styles.input}
            placeholder="Enter name"
            placeholderTextColor="#666"
            value={name}
            onChangeText={setName}
            autoCapitalize="words"
            autoFocus
          />
        </View>

        {/* Age Field */}
        <View style={styles.fieldGroup}>
          <Text style={styles.label}>Age (years) *</Text>
          <TextInput
            style={styles.input}
            placeholder="Enter age"
            placeholderTextColor="#666"
            value={age}
            onChangeText={setAge}
            keyboardType="numeric"
          />
        </View>

        {/* Weight Field */}
        <View style={styles.fieldGroup}>
          <Text style={styles.label}>Weight (kg)</Text>
          <TextInput
            style={styles.input}
            placeholder="Enter weight (optional)"
            placeholderTextColor="#666"
            value={weight}
            onChangeText={setWeight}
            keyboardType="numeric"
          />
        </View>

        {/* Height Field */}
        <View style={styles.fieldGroup}>
          <Text style={styles.label}>Height (cm)</Text>
          <TextInput
            style={styles.input}
            placeholder="Enter height (optional)"
            placeholderTextColor="#666"
            value={height}
            onChangeText={setHeight}
            keyboardType="numeric"
          />
        </View>

        {/* Save Button */}
        <TouchableOpacity style={styles.saveButton} onPress={handleSave}>
          <Text style={styles.saveButtonText}>Create Profile</Text>
        </TouchableOpacity>

        <Text style={styles.note}>
          * Required fields{'\n'}
          You can update weight and height later in the profile settings.
        </Text>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  header: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#1a1a1a',
  },
  backText: {
    color: '#7c3aed',
    fontSize: 16,
    width: 60,
  },
  headerTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 20,
  },
  fieldGroup: {
    marginBottom: 24,
  },
  label: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 12,
    padding: 16,
    color: '#fff',
    fontSize: 16,
  },
  saveButton: {
    backgroundColor: '#7c3aed',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    marginTop: 16,
    shadowColor: '#7c3aed',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  note: {
    color: '#666',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 20,
    lineHeight: 20,
  },
});

