import React, { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  Alert,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { useRouter } from 'expo-router';
import { saveProfile, setActiveProfileId, saveVital } from '../services/supabaseStorage';
import { Profile } from '../types';

export default function OnboardingProfileScreen() {
  const router = useRouter();
  const [name, setName] = useState('');
  const [age, setAge] = useState('');
  const [weight, setWeight] = useState('');
  const [height, setHeight] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleProceed = async () => {
    // Validation
    if (!name.trim()) {
      Alert.alert('Missing Information', 'Please enter your name');
      return;
    }

    if (!age || isNaN(Number(age)) || Number(age) <= 0 || Number(age) > 150) {
      Alert.alert('Invalid Age', 'Please enter a valid age (1-150)');
      return;
    }

    if (weight && (isNaN(Number(weight)) || Number(weight) <= 0)) {
      Alert.alert('Invalid Weight', 'Please enter a valid weight');
      return;
    }

    if (height && (isNaN(Number(height)) || Number(height) <= 0)) {
      Alert.alert('Invalid Height', 'Please enter a valid height');
      return;
    }

    setIsLoading(true);

    try {
      // Create user profile (ID will be generated by Supabase)
      const userProfile: Profile = {
        id: '', // Will be set by saveProfile
        name: name.trim(),
        age: Number(age),
        relation: 'Self',
      };

      await saveProfile(userProfile);
      await setActiveProfileId(userProfile.id); // Now has the generated UUID

      // Save vitals if provided
      if (weight) {
        await saveVital(userProfile.id, {
          type: 'weight',
          value: Number(weight),
          unit: 'kg',
          date: new Date().toISOString(),
          isDaily: false,
        });
      }

      if (height) {
        await saveVital(userProfile.id, {
          type: 'height',
          value: Number(height),
          unit: 'cm',
          date: new Date().toISOString(),
          isDaily: false,
        });
      }

      // Save age as vital
      await saveVital(userProfile.id, {
        type: 'age',
        value: Number(age),
        unit: 'years',
        date: new Date().toISOString(),
        isDaily: false,
      });

      // Navigate to home
      router.replace('/home');
    } catch (error) {
      console.error('Failed to create profile:', error);
      Alert.alert('Error', 'Failed to create profile. Please try again.');
      setIsLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView
      style={styles.container}
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
    >
      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.content}
        keyboardShouldPersistTaps="handled"
      >
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.emoji}>👋</Text>
          <Text style={styles.title}>Welcome!</Text>
          <Text style={styles.subtitle}>
            Let's get to know more about you
          </Text>
        </View>

        {/* Form Fields */}
        <View style={styles.form}>
          {/* Name */}
          <View style={styles.fieldGroup}>
            <Text style={styles.label}>Name *</Text>
            <TextInput
              style={styles.input}
              placeholder="Enter your name"
              placeholderTextColor="#666"
              value={name}
              onChangeText={setName}
              autoCapitalize="words"
              autoFocus
            />
          </View>

          {/* Age */}
          <View style={styles.fieldGroup}>
            <Text style={styles.label}>Age (years) *</Text>
            <TextInput
              style={styles.input}
              placeholder="Enter your age"
              placeholderTextColor="#666"
              value={age}
              onChangeText={setAge}
              keyboardType="numeric"
            />
          </View>

          {/* Weight */}
          <View style={styles.fieldGroup}>
            <Text style={styles.label}>Weight (kg)</Text>
            <TextInput
              style={styles.input}
              placeholder="Enter your weight (optional)"
              placeholderTextColor="#666"
              value={weight}
              onChangeText={setWeight}
              keyboardType="numeric"
            />
          </View>

          {/* Height */}
          <View style={styles.fieldGroup}>
            <Text style={styles.label}>Height (cm)</Text>
            <TextInput
              style={styles.input}
              placeholder="Enter your height (optional)"
              placeholderTextColor="#666"
              value={height}
              onChangeText={setHeight}
              keyboardType="numeric"
            />
          </View>
        </View>

        {/* Proceed Button */}
        <TouchableOpacity
          style={[styles.proceedButton, isLoading && styles.proceedButtonDisabled]}
          onPress={handleProceed}
          disabled={isLoading}
        >
          <Text style={styles.proceedButtonText}>
            {isLoading ? 'Creating Profile...' : 'Proceed'}
          </Text>
        </TouchableOpacity>

        <Text style={styles.note}>
          * Required fields{'\n'}
          You can add more details later
        </Text>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 32,
    paddingTop: 80,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    marginBottom: 48,
  },
  emoji: {
    fontSize: 48,
    marginBottom: 16,
  },
  title: {
    color: '#fff',
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  subtitle: {
    color: '#888',
    fontSize: 18,
    textAlign: 'center',
    lineHeight: 26,
  },
  form: {
    marginBottom: 32,
  },
  fieldGroup: {
    marginBottom: 24,
  },
  label: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 12,
    padding: 16,
    color: '#fff',
    fontSize: 16,
  },
  proceedButton: {
    backgroundColor: '#7c3aed',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    shadowColor: '#7c3aed',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  proceedButtonDisabled: {
    backgroundColor: '#666',
    opacity: 0.6,
  },
  proceedButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  note: {
    color: '#666',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 20,
    lineHeight: 20,
  },
});

